// Miuix Flutter 移植版 - GlassStyles（自动生成）
// 源自 compose-miuix-ui/miuix 的 miuix-glass，基准 3f7debbf。
// 由 tool/gen_os4_assets.mjs 生成，请勿手改。
// SPDX-License-Identifier: Apache-2.0

import 'package:flutter/painting.dart';
import 'miuix_glass_style.dart';

/// 对应 Kotlin GlassStyles：全部 35 组源端材质参数。
class MiuixGlassStyles {
  MiuixGlassStyles._();
  static const commonSmallThin = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.2,
      saturation: 2.0,
      brightness: 0.24,
      darker: 0.26,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.15,
      colorWhite: 0.0,
      colorMix: 0.4,
      colorPow: 1.5,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 50.0,
      pow: 4.0,
      thickness: 60.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 2.0, strength: 0.6),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.4,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 1.5),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 30.0, big: 500.0),
  );
  static const commonSmallNormal = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.0,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.15,
      saturation: 2.0,
      brightness: 0.26,
      darker: 0.26,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.0,
      tint: Color.from(alpha: 1, red: 0.0, green: 0.0, blue: 0.0),
      tintStrength: 0.42,
      colorWhite: 0.15,
      colorMix: 0.4,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 16.0,
      pow: 1.4,
      thickness: 100.0,
      reflectOffset: 1000.0,
    ),
    reflect: MiuixGlassReflect(lighten: 0.75, strength: 1.5),
    light: MiuixGlassLight(
      directionX: 0.6,
      directionY: -1.0,
      directionZ: 0.0,
      intensity: 1.0,
      oppositeIntensity: 1.4,
      angleRange: 0.8,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 150.0, big: 500.0),
  );
  static const commonSmallRegular = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.8,
      curveD: 1.2,
      amount: 0.24,
      saturation: 1.4,
      brightness: 0.14,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 0.9,
    ),
    inner: MiuixGlassInner(
      bottom: 0.01,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.05,
      colorWhite: 0.3,
      colorMix: 0.5,
      colorPow: 1.5,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 18.0,
      pow: 1.6,
      thickness: 100.0,
      reflectOffset: 110.0,
    ),
    reflect: MiuixGlassReflect(lighten: 0.8, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.5,
      directionY: 0.5,
      directionZ: 0.0,
      intensity: 1.1,
      oppositeIntensity: 0.5,
      angleRange: 0.3,
    ),
    refract: MiuixGlassRefract(ior: 1.4),
    background: MiuixGlassBackground(
      saturation: 1.0,
      brightness: 0.08,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 8.0, big: 500.0),
  );
  static const commonSmallSemibold = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.2,
      saturation: 2.6,
      brightness: 0.22,
      darker: 0.26,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.0,
      colorWhite: 0.0,
      colorMix: 0.4,
      colorPow: 0.97,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 60.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 2.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.5,
      directionY: 0.5,
      directionZ: -0.8,
      intensity: 1.2,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const commonSmallBold = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.42,
      curveB: 0.22,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.24,
      saturation: 1.4,
      brightness: 0.28,
      darker: 0.4,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.1,
      colorWhite: 0.2,
      colorMix: 0.3,
      colorPow: 1.0,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.6,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 4.0),
    background: MiuixGlassBackground(
      saturation: 2.6,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const commonMediumThinLow = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.2,
      saturation: 1.5,
      brightness: 0.2,
      darker: 0.1,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.05,
      colorWhite: 0.0,
      colorMix: 0.3,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 60.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.6),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.2,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 2.0),
    background: MiuixGlassBackground(
      saturation: 1.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const commonMediumThinHigh = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.6,
      curveC: 0.0,
      curveD: 0.3,
      amount: 0.2,
      saturation: 1.5,
      brightness: 0.24,
      darker: 0.1,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.1,
      colorWhite: 0.0,
      colorMix: 0.3,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 60.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.6),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 0.9,
      oppositeIntensity: 0.3,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const commonMediumRegularLowLight = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.2,
      saturation: 2.0,
      brightness: 0.2,
      darker: 0.0,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.04,
      tint: Color.from(alpha: 1, red: 0.9, green: 0.9, blue: 0.9),
      tintStrength: 1.0,
      colorWhite: 0.0,
      colorMix: 1.0,
      colorPow: 1.0,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.4,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const commonMediumRegularHighLight = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.2,
      saturation: 2.0,
      brightness: 0.1,
      darker: 0.0,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.02,
      tint: Color.from(alpha: 1, red: 0.9, green: 0.9, blue: 0.9),
      tintStrength: 1.0,
      colorWhite: 0.0,
      colorMix: 1.0,
      colorPow: 1.0,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.4,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const commonMediumRegularDark = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.2,
      saturation: 3.0,
      brightness: 0.2,
      darker: 0.0,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.04,
      tint: Color.from(alpha: 1, red: 0.06, green: 0.06, blue: 0.06),
      tintStrength: 0.4,
      colorWhite: 0.0,
      colorMix: 0.8,
      colorPow: 1.5,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 2.4,
      oppositeIntensity: 1.6,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const commonMediumBoldLight = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.5,
      saturation: 1.2,
      brightness: 0.06,
      darker: 0.1,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 2.0,
      colorWhite: 0.0,
      colorMix: 0.3,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 72.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.0,
      oppositeIntensity: 0.6,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 40.0, big: 500.0),
  );
  static const commonMediumBoldDark = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.2,
      saturation: 2.0,
      brightness: 0.14,
      darker: 0.1,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.02,
      tint: Color.from(alpha: 1, red: 0.27, green: 0.27, blue: 0.27),
      tintStrength: 0.6,
      colorWhite: 0.0,
      colorMix: 0.2,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 72.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 3.0,
      oppositeIntensity: 2.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 40.0, big: 500.0),
  );
  static const commonMediumBoldLow = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 2.0,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.2,
      saturation: 1.2,
      brightness: 0.0,
      darker: 0.4,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.02,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.1,
      colorWhite: 0.26,
      colorMix: 0.3,
      colorPow: 1.8,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 50.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1000.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 0.8,
      oppositeIntensity: 0.6,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 40.0, big: 500.0),
  );
  static const commonLargeRegular = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.0,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.15,
      saturation: 2.2,
      brightness: 0.08,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.1,
      colorWhite: 0.15,
      colorMix: 0.4,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 50.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.6,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.6,
      oppositeIntensity: 0.8,
      angleRange: 1.0,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 80.0, big: 500.0),
  );
  static const commonLargeDemibold = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 1.55,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.56,
      saturation: 2.0,
      brightness: 0.18,
      darker: 0.26,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 1.0,
      colorWhite: 0.6,
      colorMix: 0.9,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 50.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.6,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 2.0,
      oppositeIntensity: 1.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 50.0, big: 500.0),
  );
  static const bionicMediumThin = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.0,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.15,
      saturation: 1.4,
      brightness: 0.08,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.15,
      colorWhite: 0.15,
      colorMix: 0.4,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 60.0,
      reflectOffset: 1000.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.2,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 2.4,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 40.0, big: 500.0),
  );
  static const bionicMediumNormal = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.42,
      curveB: 0.22,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.24,
      saturation: 1.4,
      brightness: -0.02,
      darker: 0.3,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.1,
      colorWhite: 0.2,
      colorMix: 0.3,
      colorPow: 1.0,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.6,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 4.0),
    background: MiuixGlassBackground(
      saturation: 2.6,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const bionicMediumNormalMotion = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.42,
      curveB: 0.22,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.24,
      saturation: 1.4,
      brightness: -0.02,
      darker: 0.3,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.1,
      colorWhite: 0.2,
      colorMix: 0.3,
      colorPow: 1.0,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.6,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 4.0),
    background: MiuixGlassBackground(
      saturation: 2.6,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const bionicMediumRegular = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.78,
      curveB: 0.36,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.3,
      saturation: 1.8,
      brightness: -0.18,
      darker: 0.1,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.1,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.15,
      colorWhite: 0.16,
      colorMix: 0.3,
      colorPow: 1.1,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 2.6,
      oppositeIntensity: 1.2,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 2.0,
      brightness: -0.2,
      burn: 1.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const bionicMediumDemiboldMotion = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.42,
      curveB: 0.22,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.2,
      saturation: 2.0,
      brightness: -0.02,
      darker: 0.3,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 0.2,
      colorWhite: 0.0,
      colorMix: 0.2,
      colorPow: 0.4,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 3.0,
      oppositeIntensity: 2.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 4.0),
    background: MiuixGlassBackground(
      saturation: 2.6,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const bionicMediumSemiboldMotion = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 1.3,
      curveB: 0.64,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.52,
      saturation: 2.0,
      brightness: -0.02,
      darker: 0.3,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 1.0, green: 1.0, blue: 1.0),
      tintStrength: 1.4,
      colorWhite: 0.15,
      colorMix: 0.9,
      colorPow: 0.4,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 3.0,
      oppositeIntensity: 2.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 4.0),
    background: MiuixGlassBackground(
      saturation: 2.6,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const tintPurple = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.2,
      curveC: 0.06,
      curveD: 1.0,
      amount: 0.3,
      saturation: 1.0,
      brightness: 0.6,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.0,
      tint: Color.from(alpha: 1, red: 0.44, green: 0.37, blue: 1.0),
      tintStrength: 0.6,
      colorWhite: 0.5,
      colorMix: 0.8,
      colorPow: 1.6,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.6),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.4,
      oppositeIntensity: 1.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const tintOrange = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.2,
      curveC: 0.06,
      curveD: 1.0,
      amount: 0.3,
      saturation: 1.0,
      brightness: 0.6,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.0,
      tint: Color.from(alpha: 1, red: 0.99, green: 0.41, blue: 0.15),
      tintStrength: 0.6,
      colorWhite: 0.5,
      colorMix: 0.8,
      colorPow: 1.6,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.6),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.0,
      oppositeIntensity: 0.8,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const tintBlue = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.2,
      curveC: 0.06,
      curveD: 1.0,
      amount: 0.3,
      saturation: 1.0,
      brightness: 0.6,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 0.35, green: 0.45, blue: 0.65),
      tintStrength: 0.8,
      colorWhite: 0.5,
      colorMix: 0.6,
      colorPow: 1.45,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 0.75, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.4,
      oppositeIntensity: 1.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const tintYellow = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.2,
      curveC: 0.06,
      curveD: 1.0,
      amount: 0.3,
      saturation: 1.0,
      brightness: 0.6,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 0.99, green: 0.78, blue: 0.15),
      tintStrength: 0.6,
      colorWhite: 0.5,
      colorMix: 0.6,
      colorPow: 1.45,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 0.75, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.0,
      oppositeIntensity: 0.6,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const tintBrown = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.2,
      curveC: 0.06,
      curveD: 1.0,
      amount: 0.3,
      saturation: 2.0,
      brightness: 0.6,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 0.38, green: 0.26, blue: 0.22),
      tintStrength: 0.8,
      colorWhite: 0.5,
      colorMix: 0.6,
      colorPow: 1.45,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 0.75, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.8,
      oppositeIntensity: 1.2,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 36.0, big: 500.0),
  );
  static const tintBlackThin = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.0,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.15,
      saturation: 2.0,
      brightness: 0.18,
      darker: 0.26,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.05,
      tint: Color.from(alpha: 1, red: 0.0, green: 0.0, blue: 0.0),
      tintStrength: 0.3,
      colorWhite: 0.15,
      colorMix: 0.4,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 50.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.6,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 2.0,
      oppositeIntensity: 1.6,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 50.0, big: 500.0),
  );
  static const tintBlackNormal = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.0,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.15,
      saturation: 2.0,
      brightness: 0.3,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.02,
      tint: Color.from(alpha: 1, red: 0.06, green: 0.06, blue: 0.06),
      tintStrength: 0.5,
      colorWhite: 0.15,
      colorMix: 0.4,
      colorPow: 1.36,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 72.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1000.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.4, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 2.6,
      oppositeIntensity: 1.6,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 3.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 40.0, big: 500.0),
  );
  static const tintBlackRegular = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.42,
      curveB: 0.22,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.2,
      saturation: 1.4,
      brightness: 0.1,
      darker: 0.3,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.02,
      tint: Color.from(alpha: 1, red: 0.06, green: 0.06, blue: 0.06),
      tintStrength: 0.7,
      colorWhite: 0.2,
      colorMix: 0.3,
      colorPow: 1.0,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 3.4,
      oppositeIntensity: 2.6,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 4.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const tintBlackDemibold = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.0,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.15,
      saturation: 3.0,
      brightness: 0.3,
      darker: 0.2,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.0,
      tint: Color.from(alpha: 1, red: 0.06, green: 0.06, blue: 0.06),
      tintStrength: 0.6,
      colorWhite: 0.15,
      colorMix: 0.4,
      colorPow: 1.36,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1000.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 0.6),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 3.0,
      oppositeIntensity: 2.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 40.0, big: 500.0),
  );
  static const tintBlackHeavy = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 2.0,
      curveB: 2.0,
      curveC: 0.5,
      curveD: 0.8,
      amount: 0.2,
      saturation: 1.2,
      brightness: 0.0,
      darker: 0.4,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.02,
      tint: Color.from(alpha: 1, red: 0.06, green: 0.06, blue: 0.06),
      tintStrength: 0.4,
      colorWhite: 0.26,
      colorMix: 0.3,
      colorPow: 1.8,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 72.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1000.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.0, strength: 0.8),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.6,
      oppositeIntensity: 1.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 3.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 40.0, big: 500.0),
  );
  static const tintRedMotion = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.42,
      curveB: 0.22,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.8,
      saturation: 2.0,
      brightness: 0.2,
      darker: 0.6,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.06,
      tint: Color.from(alpha: 1, red: 1.0, green: 0.31, blue: 0.27),
      tintStrength: 1.0,
      colorWhite: 0.3,
      colorMix: 1.0,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 3.0,
      oppositeIntensity: 1.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 4.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const tintGreenMotion = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.42,
      curveB: 0.22,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.8,
      saturation: 2.0,
      brightness: 0.2,
      darker: 0.6,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.06,
      tint: Color.from(alpha: 1, red: 0.25, green: 0.84, blue: 0.35),
      tintStrength: 1.0,
      colorWhite: 0.3,
      colorMix: 1.0,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 3.0,
      oppositeIntensity: 1.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 4.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const tintBlueMotion = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.42,
      curveB: 0.22,
      curveC: 0.24,
      curveD: 0.0,
      amount: 0.8,
      saturation: 2.0,
      brightness: 0.2,
      darker: 0.6,
      darkerStart: 0.6,
      darkerEnd: 1.0,
    ),
    inner: MiuixGlassInner(
      bottom: 0.06,
      tint: Color.from(alpha: 1, red: 0.2, green: 0.51, blue: 1.0),
      tintStrength: 1.0,
      colorWhite: 0.3,
      colorMix: 1.0,
      colorPow: 1.2,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 80.0,
      reflectOffset: 1200.0,
    ),
    reflect: MiuixGlassReflect(lighten: 1.2, strength: 1.0),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 3.0,
      oppositeIntensity: 1.0,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 4.0),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 120.0, big: 120.0),
  );
  static const tintBlueNormal = MiuixGlassStyle(
    blend: MiuixGlassBlend(
      curveA: 0.5,
      curveB: 1.0,
      curveC: 0.0,
      curveD: 1.0,
      amount: 0.2,
      saturation: 2.0,
      brightness: 1.0,
      darker: 0.0,
      darkerStart: 0.6,
      darkerEnd: 0.8,
    ),
    inner: MiuixGlassInner(
      bottom: 0.0,
      tint: Color.from(alpha: 1, red: 0.2, green: 0.51, blue: 1.0),
      tintStrength: 1.5,
      colorWhite: 0.0,
      colorMix: 0.4,
      colorPow: 0.92,
      alpha: 1.0,
    ),
    edge: MiuixGlassEdge(
      width: 60.0,
      pow: 4.0,
      thickness: 60.0,
      reflectOffset: 600.0,
    ),
    reflect: MiuixGlassReflect(lighten: 2.0, strength: 0.6),
    light: MiuixGlassLight(
      directionX: -0.4,
      directionY: 0.6,
      directionZ: -0.8,
      intensity: 1.0,
      oppositeIntensity: 0.6,
      angleRange: 1.4,
    ),
    refract: MiuixGlassRefract(ior: 1.5),
    background: MiuixGlassBackground(
      saturation: 0.0,
      brightness: 0.0,
      burn: 0.0,
      unShade: 0.0,
    ),
    blur: MiuixGlassBlur(small: 30.0, big: 500.0),
  );
  static const values = <String, MiuixGlassStyle>{
    'commonSmallThin': commonSmallThin,
    'commonSmallNormal': commonSmallNormal,
    'commonSmallRegular': commonSmallRegular,
    'commonSmallSemibold': commonSmallSemibold,
    'commonSmallBold': commonSmallBold,
    'commonMediumThinLow': commonMediumThinLow,
    'commonMediumThinHigh': commonMediumThinHigh,
    'commonMediumRegularLowLight': commonMediumRegularLowLight,
    'commonMediumRegularHighLight': commonMediumRegularHighLight,
    'commonMediumRegularDark': commonMediumRegularDark,
    'commonMediumBoldLight': commonMediumBoldLight,
    'commonMediumBoldDark': commonMediumBoldDark,
    'commonMediumBoldLow': commonMediumBoldLow,
    'commonLargeRegular': commonLargeRegular,
    'commonLargeDemibold': commonLargeDemibold,
    'bionicMediumThin': bionicMediumThin,
    'bionicMediumNormal': bionicMediumNormal,
    'bionicMediumNormalMotion': bionicMediumNormalMotion,
    'bionicMediumRegular': bionicMediumRegular,
    'bionicMediumDemiboldMotion': bionicMediumDemiboldMotion,
    'bionicMediumSemiboldMotion': bionicMediumSemiboldMotion,
    'tintPurple': tintPurple,
    'tintOrange': tintOrange,
    'tintBlue': tintBlue,
    'tintYellow': tintYellow,
    'tintBrown': tintBrown,
    'tintBlackThin': tintBlackThin,
    'tintBlackNormal': tintBlackNormal,
    'tintBlackRegular': tintBlackRegular,
    'tintBlackDemibold': tintBlackDemibold,
    'tintBlackHeavy': tintBlackHeavy,
    'tintRedMotion': tintRedMotion,
    'tintGreenMotion': tintGreenMotion,
    'tintBlueMotion': tintBlueMotion,
    'tintBlueNormal': tintBlueNormal,
  };
  static MiuixGlassStyle forTheme(bool isDark) =>
      isDark ? commonMediumRegularDark : commonMediumRegularLowLight;
}
